spring:
  application:
    name: job-service
  profiles:
    active: dev
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8088/}

  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"