server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/thirdparty
    username: postgres
    password: 12345678
    hikari:
      poolName: Hikari
      maximumPoolSize: 5
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: db_user
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  app:
    oauth-url: http://localhost:${server.port}/oauth2/token

security:
  client-id: ${CLIENT_ID:project}
  client-secret: ${CLIENT_SECRET:secret}
  jwt:
    duration: ${JWT_DURATION:6000}