services:
  zookeeper:
    platform: linux/amd64
    image: apache/kafka:4.1.1
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    platform: linux/amd64
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181