spring:
  application:
    name: gateway-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8088/}
#  cloud:
#    gateway:
#      routes:
#        - id: login-rewrite
#          uri: lb://authorization-service
#          predicates:
#            - Path=/login
#            - Method=POST
#          filters:
#            - RewritePath=/login, /api/authen/oauth2/token